
[DEFAULT]

### INPUTS ###
# output path
output_dir=tutorial_output/solweig
# working path
working_dir=/home/ginira/Thesis/.qgis_plugins/processing_umep/temp
# parameters json file
para_json_path=tutorial_output/solweig/solweig_parameters.json
# Input ground and building dsm
filepath_dsm=Data/Goteborg_SWEREF99_1200/DSM_KRbig.tif
# Input vegetation dsm
filepath_cdsm=Data/Goteborg_SWEREF99_1200/CDSM_KRbig.asc
# Input trunkzone vegetation dsm
filepath_tdsm=
# Input Digital Elevation Model
filepath_dem=Data/Goteborg_SWEREF99_1200/DEM_KRbig.tif
# Input Land cover dataset
filepath_lc=Data/Goteborg_SWEREF99_1200/landcover.tif
# Input wall height raster
filepath_wh=tutorial_output/wall_height.tif
# Input wall aspect raster
filepath_wa=tutorial_output/wall_aspect.tif
# Skyview factor files
input_svf=tutorial_output/svf/svfs.zip
# Input file for anisotrophic sky
input_aniso=
# Point of Interest file for ground
poi_file=
poi_field=
# Input file for wall temperture scheme (Wallenberg et al. 2025)
input_wall=
# Point of Interest file for walls
woi_file=
woi_field=
# input meteorolgical file (i.e. forcing file)
input_met=Data/Goteborg_SWEREF99_1200/gbg19970606_2015a.txt

## input settings ##
# dates
# option to execute solweig outside of osgeo/qgis environment
standalone=0
# estimate diffuse and global shortwve radiation from global radiation (1)
onlyglobal=1
# use vegetation scheme (lindberg and grimmond, 2011, TAAC)
usevegdem=1
# consider leaf on trees full year (1)
conifer_bool=0
# consider person as a cylinder (1) or a box (0)
cyl=1
# Location of model domain
lat=57.706161175026
lon=11.961755536059222
#utc time given in meteorological forcing file
utc=0
# scale between horisontal and vertical resolution (1 = 1 meter pixel reolution, 0.5 = 2)
scale=1.0
# Set to 1 if an EPW file is used as meteorological forcing data
useepwfile=0
# land cover scheme activated (1) (Lindberg et al. 2016 UC)
landcover=1
# use dem and dsm to identify building pixels (0) else, land cover will be used (0)
demforbuild=1
# use anisotrphic sky (Wallenberg et al. XXXX and Wallenberg et al. XXXX)
aniso=0
# use wall surface temperature scheme (Wallenberg et al. 2025, GMD)
wallscheme=0
# If building materials is not included in lc, then this is used for all buildings (Wood, Brick or Concrete)
walltype=100
# output settings
outputtmrt=1
outputkup=1
outputkdown=1
outputlup=1
outputldown=1
outputsh=1
savebuild=0
outputkdiff=0
outputtreeplanter=0
wallnetcdf=0
#-------------------------------------------------------
# dates - used if an EPW-file is used
#-------------------------------------------------------
# year,month,day,hour	## the start date/time for period of interest
date1=2018,5,1,0
# year,month,day,hour	# end date/time
date2=2018,8,1,18

